<?php

return [
    [
        'shipping_id' => 5470,
        'name'        => 'UPS Standard 0-1kg',
        'min_weight'  => 0,
        'max_weight'  => 1,
    ],
    [
        'shipping_id' => 5471,
        'name'        => 'UPS Standard 1-2kg',
        'min_weight'  => 1,
        'max_weight'  => 2,
    ],
    [
        'shipping_id' => 5472,
        'name'        => 'UPS Standard 2-3kg',
        'min_weight'  => 2,
        'max_weight'  => 3,
    ],
    [
        'shipping_id' => 5473,
        'name'        => 'UPS Standard 3-4kg',
        'min_weight'  => 3,
        'max_weight'  => 4,
    ],
    [
        'shipping_id' => 5474,
        'name'        => 'UPS Standard 4-5kg',
        'min_weight'  => 4,
        'max_weight'  => 5,
    ],
    [
        'shipping_id' => 5475,
        'name'        => 'UPS Standard 5-6kg',
        'min_weight'  => 5,
        'max_weight'  => 6,
    ],
    [
        'shipping_id' => 5476,
        'name'        => 'UPS Standard 6-7kg',
        'min_weight'  => 6,
        'max_weight'  => 7,
    ],
    [
        'shipping_id' => 5477,
        'name'        => 'UPS Standard 7-8kg',
        'min_weight'  => 7,
        'max_weight'  => 8,
    ],
    [
        'shipping_id' => 5478,
        'name'        => 'UPS Standard 8-9kg',
        'min_weight'  => 8,
        'max_weight'  => 9,
    ],
    [
        'shipping_id' => 5479,
        'name'        => 'UPS Standard 9-10kg',
        'min_weight'  => 9,
        'max_weight'  => 10,
    ],
    [
        'shipping_id' => 5480,
        'name'        => 'UPS Standard 10-12kg',
        'min_weight'  => 10,
        'max_weight'  => 12,
    ],
    [
        'shipping_id' => 5481,
        'name'        => 'UPS Standard 12-14kg',
        'min_weight'  => 12,
        'max_weight'  => 14,
    ],
    [
        'shipping_id' => 5482,
        'name'        => 'UPS Standard 14-16kg',
        'min_weight'  => 14,
        'max_weight'  => 16,
    ],
    [
        'shipping_id' => 5483,
        'name'        => 'UPS Standard 16-18kg',
        'min_weight'  => 16,
        'max_weight'  => 18,
    ],
    [
        'shipping_id' => 5484,
        'name'        => 'UPS Standard 18-20kg',
        'min_weight'  => 18,
        'max_weight'  => 20,
    ],
    [
        'shipping_id' => 5485,
        'name'        => 'UPS Standard 20-22kg',
        'min_weight'  => 20,
        'max_weight'  => 22,
    ],
    [
        'shipping_id' => 5486,
        'name'        => 'UPS Standard 22-24kg',
        'min_weight'  => 22,
        'max_weight'  => 24,
    ],
    [
        'shipping_id' => 5487,
        'name'        => 'UPS Standard 24-26kg',
        'min_weight'  => 24,
        'max_weight'  => 26,
    ],
    [
        'shipping_id' => 5488,
        'name'        => 'UPS Standard 26-28kg',
        'min_weight'  => 26,
        'max_weight'  => 28,
    ],
    [
        'shipping_id' => 5489,
        'name'        => 'UPS Standard 28-30kg',
        'min_weight'  => 28,
        'max_weight'  => 30,
    ],
    [
        'shipping_id' => 5490,
        'name'        => 'UPS Standard 30-32kg',
        'min_weight'  => 30,
        'max_weight'  => 32,
    ],
    [
        'shipping_id' => 5491,
        'name'        => 'UPS Standard 32-34kg',
        'min_weight'  => 32,
        'max_weight'  => 34,
    ],
    [
        'shipping_id' => 5492,
        'name'        => 'UPS Standard 34-36kg',
        'min_weight'  => 34,
        'max_weight'  => 36,
    ],
    [
        'shipping_id' => 5493,
        'name'        => 'UPS Standard 36-38kg',
        'min_weight'  => 36,
        'max_weight'  => 38,
    ],
    [
        'shipping_id' => 5494,
        'name'        => 'UPS Standard 38-40kg',
        'min_weight'  => 38,
        'max_weight'  => 40,
    ],
    [
        'shipping_id' => 5495,
        'name'        => 'UPS Standard 40-42kg',
        'min_weight'  => 40,
        'max_weight'  => 42,
    ],
    [
        'shipping_id' => 5496,
        'name'        => 'UPS Standard 42-44kg',
        'min_weight'  => 42,
        'max_weight'  => 44,
    ],
    [
        'shipping_id' => 5497,
        'name'        => 'UPS Standard 44-46kg',
        'min_weight'  => 44,
        'max_weight'  => 46,
    ],
    [
        'shipping_id' => 5498,
        'name'        => 'UPS Standard 46-48kg',
        'min_weight'  => 46,
        'max_weight'  => 48,
    ],
    [
        'shipping_id' => 5499,
        'name'        => 'UPS Standard 48-50kg',
        'min_weight'  => 48,
        'max_weight'  => 50,
    ],
    [
        'shipping_id' => 5500,
        'name'        => 'UPS Standard 50-55kg',
        'min_weight'  => 50,
        'max_weight'  => 55,
    ],
    [
        'shipping_id' => 5501,
        'name'        => 'UPS Standard 55-60kg',
        'min_weight'  => 55,
        'max_weight'  => 60,
    ],
    [
        'shipping_id' => 5502,
        'name'        => 'UPS Standard 60-65kg',
        'min_weight'  => 60,
        'max_weight'  => 65,
    ],
    [
        'shipping_id' => 5503,
        'name'        => 'UPS Standard 65-70kg',
        'min_weight'  => 65,
        'max_weight'  => 70,
    ],
];
